### ISSUE TITLE
Q: How is Fox Sports article about Cloud Run & Firebase Hosting?

### ISSUE THREAD

**Issue by dweekly** [steren/awesome-cloudrun#37]
Hi, Steren. The link "Firebase hosting and Cloud Run cache" you have here links to a Fox article at https://www.theverge.com/2020/7/25/21336017/fox-sports-baseball-virtual-fans-epic-unreal-engine-empty-stadiums-mlb but it's not obvious from the article how they used Firebase hosting or Cloud Run.

**Comment by steren** [comment]
This was introduced in https://github.com/steren/awesome-cloudrun/commit/d4865baf953c6f7d9e1da0553c27677024e22dbd

Not sure why I linked to this article. Probably a copy paste error?
